// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EntityItemKeyValidator is an autogenerated mock type for the KeyValidator type
type EntityItemKeyValidator struct {
	mock.Mock
}

// ForbiddenRunes provides a mock function with given fields:
func (_m *EntityItemKeyValidator) ForbiddenRunes() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// KeyMaxLen provides a mock function with given fields:
func (_m *EntityItemKeyValidator) KeyMaxLen() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewEntityItemKeyValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewEntityItemKeyValidator creates a new instance of EntityItemKeyValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEntityItemKeyValidator(t mockConstructorTestingTNewEntityItemKeyValidator) *EntityItemKeyValidator {
	mock := &EntityItemKeyValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
